const express = require("express");
const router = express.Router();
const adminController = require("../controllers/adminController");
const { requireAdmin, requireModuleAccess } = require("../middleware/accessControl");

router.get("/notifications", requireAdmin, adminController.getNotifications);
router.post("/notifications/read-all", requireAdmin, adminController.markAllNotificationsRead);
router.post("/notifications/:id/ack", requireAdmin, adminController.acknowledgeNotification);
router.patch("/notifications/:id/read", requireAdmin, adminController.markNotificationRead);
router.patch("/notifications/:id/priority", requireAdmin, adminController.setNotificationPriority);
router.delete("/notifications/:id", requireAdmin, adminController.deleteNotification);
router.get("/overview", requireAdmin, adminController.getOverview);
router.get("/activity", requireAdmin, adminController.getActivityReport);
router.post("/activity/:id/restore", requireAdmin, adminController.restoreActivityRecord);
router.get("/employees", requireAdmin, adminController.getEmployees);
router.patch("/employees/:id/access", requireAdmin, adminController.updateEmployeeAccess);
router.get("/drivers/chats", requireModuleAccess("drivers"), adminController.getDriverChats);
router.get("/drivers/:id/messages", requireModuleAccess("drivers"), adminController.getDriverChatMessages);
router.post("/drivers/:id/messages", requireModuleAccess("drivers"), adminController.sendDriverChatMessage);
router.get("/drivers", requireModuleAccess("drivers"), adminController.getDrivers);
router.get("/finance", requireModuleAccess("finance"), adminController.getFinance);
router.post("/finance/payouts", requireModuleAccess("finance"), adminController.createPayout);
router.put("/finance/payouts/:id", requireModuleAccess("finance"), adminController.updatePayout);
router.patch("/finance/payouts/:id/status", requireModuleAccess("finance"), adminController.updatePayoutStatus);
router.delete("/finance/payouts/:id", requireModuleAccess("finance"), adminController.deletePayout);
router.get("/billing", requireModuleAccess("billing"), adminController.getBilling);
router.get("/billing/form-data", requireModuleAccess("billing"), adminController.getBillingFormData);
router.get("/billing/:id", requireModuleAccess("billing"), adminController.getInvoiceById);
router.post("/billing", requireModuleAccess("billing"), adminController.createInvoice);
router.put("/billing/:id", requireModuleAccess("billing"), adminController.updateInvoice);
router.patch("/billing/:id/status", requireModuleAccess("billing"), adminController.updateInvoiceStatus);
router.delete("/billing/:id", requireModuleAccess("billing"), adminController.deleteInvoice);
router.get("/tracking", requireModuleAccess("tracking"), adminController.getTracking);
router.get("/tracking/vehicles/:id", requireModuleAccess("tracking"), adminController.getTrackingVehicleById);
router.patch("/tracking/vehicles/:id", requireModuleAccess("tracking"), adminController.updateTrackingVehicle);
router.get("/alerts", requireModuleAccess("alerts"), adminController.getAlerts);
router.patch("/alerts/:id/status", requireModuleAccess("alerts"), adminController.updateAlertStatus);
router.get("/routes", requireModuleAccess("trips"), adminController.listRoutes);
router.post("/routes", requireModuleAccess("trips"), adminController.createRoute);
router.put("/routes/:id", requireModuleAccess("trips"), adminController.updateRoute);
router.delete("/routes/:id", requireModuleAccess("trips"), adminController.deleteRoute);
router.get("/trips/form-data", requireModuleAccess("trips"), adminController.getTripFormData);
router.get("/trips/:id", requireModuleAccess("trips"), adminController.getTripById);
router.get("/trips", requireModuleAccess("trips"), adminController.getTrips);
router.post("/trips", requireModuleAccess("trips"), adminController.createTrip);
router.put("/trips/:id", requireModuleAccess("trips"), adminController.updateTrip);
router.patch("/trips/:id/status", requireModuleAccess("trips"), adminController.updateTripStatus);
router.delete("/trips/:id", requireModuleAccess("trips"), adminController.deleteTrip);

module.exports = router;
